# Generated by Django 5.2.8 on 2025-11-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historic',
            old_name='productName',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='historic',
            name='typeOperation',
            field=models.CharField(choices=[('Input', 'Input'), ('Output', 'Output')], max_length=6),
        ),
    ]
