# Generated by Django 5.2.8 on 2025-11-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_rename_productname_historic_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historic',
            name='operationDate',
        ),
    ]
